### ISSUE TITLE
Add defer statement

### ISSUE THREAD

**Issue by mdouchement** [mdouchement/shigoto#14]
```yml
commands:
  - sh: |
      for i in {{.RANGE | splitList "\n" | join " "}}
      do
        echo "Hello $i times"
      done
    # defer will execute this command when all runners are runned (it works like Golang's defer).
    # (default: false)
    defer: true
```
