### ISSUE TITLE
Add a logrotate statement

### ISSUE THREAD

**Issue by mdouchement** [mdouchement/shigoto#15]
It must be used only when logs are stored in a file.

```yml
shigoto:
  task-name:
    logs_file: /shigoto/logs/rclone.log
    logrorate:
      size: 10M
      rotate: 7
      compress: true
```
> It should also be applied on `redirect` of the runners

https://github.com/natefinch/lumberjack
https://github.com/kjk/common/tree/main/filerotate
https://pkg.go.dev/github.com/yieldr/go-log/log/logrotate
https://github.com/easyCZ/logrotate
